### ISSUE TITLE
RuntimeError: 1033 (AWS_IO_TLS_CTX_ERROR): Failed to create tls context

### ISSUE THREAD

**Issue by apachler** [aws-samples/aws-iot-fleet-provisioning#18]
Having a problem getting the Python reference client working.

OS: Linux 
SSL Libs: openssl 1.1.1.k-1, python-pyopenssl 20.0.1-1
Python Version: 3.8

> Traceback (most recent call last):
  File "main.py", line 79, in <module>
    run_provisioning(isRotation=False)
  File "main.py", line 73, in run_provisioning
    provisioner.get_official_certs(callback)
  File "/home/apachler/Development/IOT/aws-iot-fleet-provisioning/provisioning_handler.py", line 160, in get_official_certs
    return asyncio.run(self.orchestrate_provisioning_flow(callback))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/apachler/Development/IOT/aws-iot-fleet-provisioning/provisioning_handler.py", line 164, in orchestrate_provisioning_flow
    self.core_connect()
  File "/home/apachler/Development/IOT/aws-iot-fleet-provisioning/provisioning_handler.py", line 86, in core_connect
    self.primary_MQTTClient = mqtt_connection_builder.mtls_from_path(
  File "/home/apachler/.local/lib/python3.8/site-packages/awscrt/awsiot_mqtt_connection_builder.py", line 201, in mtls_from_path
    return _builder(tls_ctx_options, **kwargs)
  File "/home/apachler/.local/lib/python3.8/site-packages/awscrt/awsiot_mqtt_connection_builder.py", line 162, in _builder
    tls_ctx = awscrt.io.ClientTlsContext(tls_ctx_options)
  File "/home/apachler/.local/lib/python3.8/site-packages/awscrt/io.py", line 410, in __init__
    self._binding = _awscrt.client_tls_ctx_new(
RuntimeError: 1033 (AWS_IO_TLS_CTX_ERROR): Failed to create tls context

**Comment by RaleighSF** [comment]
Closing with resolution (offline) being that the pub/private certs were inadvertently mix-referenced in the config.ini which netted the following error.
